// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_0s4AMZ_Vgnfvc92J_bOQ5GAEn1-CJs',
    appId: '1:830978941104:web:272e09788adb5aa27c5b75',
    messagingSenderId: '830978941104',
    projectId: 'hazriverpod',
    authDomain: 'hazriverpod.firebaseapp.com',
    storageBucket: 'hazriverpod.firebasestorage.app',
    measurementId: 'G-51Y82J1LHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtL_WUsIXE1sE4ZNhgfwEw2xfBNd0tsBU',
    appId: '1:830978941104:android:766828f7e66ad5a07c5b75',
    messagingSenderId: '830978941104',
    projectId: 'hazriverpod',
    storageBucket: 'hazriverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCJIDKAQj_tots3MEGVCWyOFMn_HK3PQ',
    appId: '1:830978941104:ios:81965b8fd78d48eb7c5b75',
    messagingSenderId: '830978941104',
    projectId: 'hazriverpod',
    storageBucket: 'hazriverpod.firebasestorage.app',
    iosBundleId: 'com.example.riverPodPractise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQCJIDKAQj_tots3MEGVCWyOFMn_HK3PQ',
    appId: '1:830978941104:ios:81965b8fd78d48eb7c5b75',
    messagingSenderId: '830978941104',
    projectId: 'hazriverpod',
    storageBucket: 'hazriverpod.firebasestorage.app',
    iosBundleId: 'com.example.riverPodPractise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_0s4AMZ_Vgnfvc92J_bOQ5GAEn1-CJs',
    appId: '1:830978941104:web:cbac387288ea15d87c5b75',
    messagingSenderId: '830978941104',
    projectId: 'hazriverpod',
    authDomain: 'hazriverpod.firebaseapp.com',
    storageBucket: 'hazriverpod.firebasestorage.app',
    measurementId: 'G-FDWL12YEBW',
  );
}
